version: 2
jobs:
  build:
    resource_class: xlarge
    docker:
      - image: wsmoses/tapir:latest

    steps:
      - checkout
      - run:
          name: submodules
          command: |
            git submodule sync
            git submodule update --init --recursive
      - run:
          name: cmake
          command: |
            mkdir build
            cd build
            cmake .. -DCMAKE_BUILD_TYPE=Release -DLLVM_TARGETS_TO_BUILD=host -DLLVM_BUILD_TESTS=ON -DLLVM_ENABLE_ASSERTIONS=ON -DLLVM_ENABLE_LTO=OFF -DLLVM_PARALLEL_COMPILE_JOBS=2 -DLLVM_PARALLEL_LINK_JOBS=1
      - run:
          name: make
          command: |
            cd build
            make -j2
      - run:
          name: test
          command: |
            cd build
            make check-all
